export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const ITEM_ROUTE = '/item'
export const BASKET_ROUTE = '/basket'